### ISSUE TITLE
some messages might get dropped due to buffered channels

### ISSUE THREAD

**Issue by HeavyHorst** [matryer/vice#15]
We use buffered channels for the sender in some queue implementations (nats, redis, sqs).
This increases the performance a lot (#12) but if we stop the transport we might leave   some messages in this channel without sending them to the message queue.

Should we flush all remaining messages to the queue if we call Stop() ?

**Comment by matryer** [comment]
Yes we should... question is, how?

**Comment by HeavyHorst** [comment]
I've got something working for nats: #20

**Comment by matryer** [comment]
Opened issues for the other implementations.
