### ISSUE TITLE
Async Behaviour varies between nsq and Nats

### ISSUE THREAD

**Issue by joeblew99** [matryer/vice#18]
nsq
- if i kill the service, send a few messages from the client, and then restart the service, the client gets the messages back that were stored inside nsqd

nats
- if i do the same, nats does not. The messages that were sent by the client are lost.

---

BTW since the API is meant to be agnostic to the underlying MQ, then can we use a string based Service factory i wonder :) I know its not proper golang, but well its a neat trick and will make testing / benching easier one might assume.

**Comment by HeavyHorst** [comment]
Nats is fire and forget with no persistence. That's by design.
If you send messages and no one is there to receive the messages the messages are lost.

NSQ has a default mem-queue-size of 10.000 messages.
I think that is the reason for your observed behavior.

NSQ-Doc:
```
-mem-queue-size int
    number of messages to keep in memory (per topic/channel) (default 10000)
```

**Comment by joeblew99** [comment]
ok makes sense. thanks

**Comment by joeblew99** [comment]
NATS provides a clustered persistence option these days. I think its out of beta too.
Might be worth trying out. Apparently the API has no changes at all, so if true its more just a matter of supplying he ability to boot it.

**Comment by HeavyHorst** [comment]
I've created a pull request to support nats streaming: #32

**Comment by joeblew99** [comment]
woooo :)

**Comment by matryer** [comment]
@joeblew99 are you happy?

**Comment by joeblew99** [comment]
well i tried it and it worked well for me. SO yes.
Will close this..
