### ISSUE TITLE
Setup Travis

### ISSUE THREAD

**Issue by matryer** [matryer/vice#22]
[![Build Status](https://travis-ci.org/matryer/vice.svg?branch=master)](https://travis-ci.org/matryer/vice)

**Comment by GeorgeMac** [comment]
Not that I am biased or anything XD, but if you want integration tests for each queue implementation, Codeship Pro lets you describe your whole CI as a docker compose style services file with a yaml workflow. If there is a container for it, you can configure it fairly trivially. I imagine you may be used to travis and stick with it, but I would be happy to open a demonstration PR if you are interested?
