### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by dc0d** [matryer/vice#48]
On the front page the documentation states **PROJECT STATUS: BETA - Aiming for v1.0 release in October 2017**.

When will `v1.0` come out (as of June 2018)?

**Comment by matryer** [comment]
Thanks for your question.

I think the interface has settled down, and I know Vice has been running in production for years in some places, so I think the time is soon.

**Comment by dc0d** [comment]
If you see fit, this should get labeled as question or get closed. I prefer it to be closed and questions move to a FAQ in the Wiki. Projects with a high number of open issues - even when most of them are not real issues - are a bit disheartening to use!

**Comment by matryer** [comment]
https://github.com/matryer/vice/releases/tag/v1.0.0
