### ISSUE TITLE
Redis queue imports fail - gopkg.in is not supported any longer

### ISSUE THREAD

**Issue by wmccracken** [matryer/vice#52]
The redis Transport is currently failing:

`vendor/gopkg.in/redis.v3/cluster.go:17:2: use of internal package github.com/xx/yy/vendor/github.com/go-redis/redis/internal not allowed
vendor/gopkg.in/redis.v3/ring.go:14:2: use of internal package github.com/xx/yy/vendor/github.com/go-redis/redis/internal/consistenthash not allowed
vendor/gopkg.in/redis.v3/cluster.go:18:2: use of internal package github.com/xx/yy/vendor/github.com/go-redis/redis/internal/hashtag not allowed
vendor/gopkg.in/redis.v3/cluster.go:19:2: use of internal package github.com/xx/yy/vendor/github.com/go-redis/redis/internal/pool not allowed
vendor/gopkg.in/redis.v3/cluster.go:20:2: use of internal package github.com/xx/yy/vendor/github.com/go-redis/redis/internal/proto not allowed
vendor/gopkg.in/redis.v3/cluster.go:21:2: use of internal package github.com/xx/yy/vendor/github.com/go-redis/redis/internal/singleflight not allowed`

This appears to be related to https://github.com/go-redis/redis/issues/665 

Updating the imports to  __github.com/go-redis/redis__ corrected the issue for me.  I'll submit a PR shortly.

**Comment by ojizero** [comment]
@wmccracken this should be fixed both in the patched version of Vice 1 (#54) as well as Vice V2. Will close this for now, please feel free to update me if you still face any other issues with it!
