### ISSUE TITLE
flaky tests because the stopped transport is reused in vicetest/test.go

### ISSUE THREAD

**Issue by HeavyHorst** [matryer/vice#8]
This function 

```go
func Transport(t *testing.T, transport vice.Transport) {
	testStandardTransportBehaviour(t, transport)
	testSendChannelsDontBlock(t, transport)
}
```

uses the same transport for both tests.The first test stops the transport at the end, which is followed by some closed channels.

I get some flaky tests in the nats client code:

```go
	go func() {
		for {
			select {
			case <-t.stopPubChan:
				return
			case msg := <-ch:
				if err := c.Publish(name, msg); err != nil {
					t.errChan <- vice.Err{Message: msg, Name: name, Err: err}
				}
			default:
			}
		}
	}()
```

```
=== RUN   TestTransport
        test.go:38: send channels shouldn't block
```

That is because the t.stopPubChan is already closed.

Maybe we should export these 2 functions
```
	testStandardTransportBehaviour(t, transport)
	testSendChannelsDontBlock(t, transport)
```
so that every queue can run these tests with a new transport.

**Comment by matryer** [comment]
Perhaps we could change the transport test to:

```
func Transport(t *testing.T, func() vice.Transport)
```

That way, the function could create the transport and we could call it twice from within there?

**Comment by HeavyHorst** [comment]
That should work. I can put a pull request together if you like.

**Comment by matryer** [comment]
That would be great.

Also, we should probably use `t.Run` for each function.

**Comment by matryer** [comment]
Did this fix it?

**Comment by HeavyHorst** [comment]
With #9 i can't reproduce this anymore.
